name: Node.js CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - devel
      - stage
      - prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '15.x'

      - run: npm install
        name: Install dependencies


      - run: npm run lint
        name: linter

      - run: CI=true npm run test
        name: Testing
      
      - run: npm run build
        name: Build 

      - name: deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if ["${{github.ref}}" == "refs/heads/devel"]; then
            aws s3 sync public/ s3://randombucketnamecodefsl-devel --delete
          elif ["${{github.ref}}" == "refs/heads/stage"]; then
            aws s3 sync public/ s3://randombucketnamecodefsl-stage --delete
          elif ["${{github.ref}}" == "refs/heads/stage"]; then
            aws s3 sync public/ s3://randombucketnamecodefsl-prod --delete
          fi
